#!/bin/bash
clear


# Color Type 9
CY="\e[96;1m" # Cyan
CyanBee="\e[5;36m" # BlueCyan
GreenBe="\e[5;32m" # Green / hijau
WhiteBe="\e[5;37m" # White / Putih
Green="\e[92;1m"
GREEN="\e[92;1m"
RED="\e[91;1m"
# Color type 38
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
ipsaya=$(wget -qO- ipinfo.io/ip)
echo -e "Memeriksa VPS Anda..."
sleep 0.5

KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/@RAIKAZUSTORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282164649858"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc

# . Liner L1
function L1() {
  echo -e "${UK}┌──────────────────────────────────────────┐ ${Suffix} "
}


# . Liner L2
function L2() {
  echo -e "${UK}└──────────────────────────────────────────┘ ${Suffix}"
}


# . Liner Horizontal
function Horizontal(){
  echo -e "${UK} ——————————————————————————————————————————— ${Suffix}"
}

  
  # // Raikazu Backend Banner
function Raikazu_Banner() {
clear
L1
echo -e "${BC}               RAIKAZU PROJECT                 ${Suffix}"
L2
}

  # // Thanks To Raikazu Tunneling
function Sc_Credit(){
sleep 2
L1
echo -e "${BC}        Terimakasih Telah Menggunakan      ${Suffix}"
echo -e "${BC}                Script Credit              ${Suffix}"
echo -e "${BC}              RAIKAZU PROJECT V1           ${Suffix}"
L2
read -p "[ Enter ] Go Back In Menu "
m-ssh
}

function ENVIRONMENT() {
L1
 echo -e "${UK}           ---[ CHANGE TITLE ]---             ${Suffix}"
L2
}

# // Submit Loading : sleep 3 & loading $!
function loading() {
clear
echo
echo
echo
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}


clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
CHATIDD=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 4)
TIMES="15"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
WAKTU=$(date | cut -d " " -f 2-10000)
clear



ENVIRONMENT
Horizontal
  echo -e ""
  echo -e " Just input a number for \033[2;32mLimit IP\033[0m"
  echo -e ""
  echo -e " \033[33m0\033[0m for No Limit"
  echo -e ""
Horizontal
echo ""
read -p " Username      : " Login
echo
read -p " Password      : " Pass
echo
read -p " Limit (IP)    : " iplimit
echo
read -p " Expired (day) : " masaaktif


sleep 2 & loading



#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
clear

cat > /var/www/html/ssh-$Login.txt <<-END
———————————————————————————————————————
 Format SSH OVPN Account
———————————————————————————————————————
Username         : $Login
Password         : $Pass
———————————————————————————————————————
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80,8080,2082,2095
Port SSH SSL WS  : 443
Port SSL/TLS     : 443-8443
Port OVPN WS SSL : 443
Port OVPN UDP    : 2200
———————————————————————————————————————
Aktif Selama     : $masaaktif Hari
Dibuat Pada      : $tnggl
Berakhir Pada    : $expe
———————————————————————————————————————
Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
———————————————————————————————————————
OVPN Download    : https://$domain:81/
———————————————————————————————————————

END

ENCH="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf]"

HTTP="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

WSS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"


#Account Auto Notif
function notif_akun() {
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b> SSH Premium Account</b>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>USER      :</b> <code>$Login</code>
<b>Password  :</b> <code>$Pass</code>
<b>DOMAIN    :</b> <code>$domain</code>
<b>WILCARD   :</b> <code>bug.$domain</code>
<b>EXPIRED ON:</b> <code>$expe</code>
<b>QUOTA     :</b> <code>$Quota</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<code>Port OpenSSH  : 443,80,22</code>
<code>Port Dropbear : 443,109</code>
<code>Port SSH WS   : 80,8080,8081-9999</code>
<code>Port SSH UDP  : 1-65535,1000-7000</code>
<code>Port SSH WS   : 443</code>
<code>Port SSL/TLS  : 443-900</code>
<code>Port OVPN WS  : 443</code>
<code>Port OVPN SSL : 443</code>
<code>Port OVPN TCP : 443,1194</code>
<code>Port OVPN UDP : 2200</code>
<code>BadVPN UDP    : 7100,7300,7300</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>HTTP CUSTOM WS  :</b>
<code>$domain:80@$Login:$Pass</code>
<b>HTTP CUSTOM SSL :</b>
<code>$domain:443@$Login:$Pass</code> 
<b>SSH UDP VIRAL   :</b>
<code>$domain:1-65535@$Login:$Pass</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>PAYLOAD HTTP/SSL :</b> 
<code>$HTTP</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>PAYLOAD WSS SSL  :</b> 
<code>$WSS</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>PAYLOAD ENHANCED :</b> 
<code>$ENCH</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>OPENVPN  : 
https://$domain:81/</b>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>LINK SAVE ACCOUNT : 
https://$domain:81/ssh-$Login.txt</b>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>AKTIF SELAMA :</b> <code>$masaaktif HARI</code>
<b>DETAIL       :</b> <code>$WAKTU</code>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b>
<b>AUTO SCRIPT BY @RAIKAZUSTORE</b>
<b>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</b> "
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}


#Auto Notif Transaksi Jangan Di Ubah
function notif_addhost() {
CHATIDD="$CHATIDD"
KEY="$KEY"
TIMES="$TIMES"
URL="$URL"
TEXTT="
<code>◇━━━━━━━━━━━━━━━━◇</code>
<b>⚡TRANSAKSI SUCCESS⚡</b>
<code>◇━━━━━━━━━━━━━━━━◇</code>
<b>DATE   :</b> <code>$WAKTU</code>
<b>DETAIL :</b> <code>TRX SSH</code>
<b>ISP    :</b> <code>$ISP $CITY</code>
<b>DURASI :</b> <code>$masaaktif HARI</code>
<code>◇━━━━━━━━━━━━━━━━◇</code>
<i>AutoNotif Create Akun From Server..</i> 
"'&reply_markup={"inline_keyboard":[[{"text":"RAIKAZU🛍️","url":"https://t.me/RAIKAZUSTORE"},{"text":"WHATSHAPP🚀","url":"wa.me/+6282164649858"}]]}'
curl -s --max-time $TIMES -d "chat_id=$CHATIDD&disable_web_page_preview=1&text=$TEXTT&parse_mode=html" $URL >/dev/null
}


# Details ACcount
function Details_Ssh(){
Raikazu_Banner
L1
echo -e "${UK}           ---[ SSH  PREMIUM ]---             ${Suffix}"
L2
echo -e "Remark      : $Login"
echo -e "Password    : $Pass"
echo -e "Limit Ip    : ${iplimit} Devic"
echo -e "Domain      : $domain"
echo -e "ISP         : $ISP"
echo -e "OpenSSH     : 443, 80, 22"
echo -e "Port UDP    : 1-65535"
echo -e "SSH WS      : 80,8080,8880,2082"
echo -e "SSL/TLS     : 443"
echo -e "OVPN UDP    : 2200"
}



function Copy_Faste(){
  L1
echo -e "Port 80     : $domain:80@$Login:$Pass"
echo -e "Port 443    : $domain:443@$Login:$Pass"
echo -e "Udp Custom  : $domain:1-65535@$Login:$Pass"
echo -e "OpenVpn     : https://$domain:81/"
echo -e "Account     : https://$domain:81/ssh-$Login.txt"
L2
}



function Details_Payload(){
L1
echo -e "Payload WS  : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
Horizontal
echo -e "Payload TLS : GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
Horizontal
echo -e "Payload ENCD: HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf"
L2
}



function Expiry_Details(){
echo -e "${UK}EXPIRED IN  : $masaaktif Day${Suffix}"
}


Raikazu_Banner
loading
ENVIRONMENT
Details_Ssh
Copy_Faste
Details_Payload
Expiry_Details
notif_akun
notif_addhost
Sc_Credit