#!/bin/bash
clear
IP=$(curl -sS ipv4.icanhazip.com);
clear


date=$(date +"%Y-%m-%d");
Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"

Info="${Green_font_prefix}[ON]${Font_color_suffix}"
Error="${Red_font_prefix}[OFF]${Font_color_suffix}"

cek=$(grep -c -E "^# BEGIN_Backup" /etc/crontab)
if [[ "$cek" = "1" ]]; then
sts="${Info}"
else
sts="${Error}"
fi


function start() {
email=$(cat /home/email)
if [[ "$email" = "" ]]; then


# // input Email
echo "Please enter your email"
read -rp "Email : " -e email
cat <<EOF>>/home/email
$email
EOF
fi
cat << EOF >> /etc/crontab
# BEGIN_Backup
5 0 * * * root backup
# END_Backup
EOF
service cron restart
sleep 1
echo " Please Wait"
clear
echo " Autobackup Has Been Started"
echo " Data Will Be Backed Up Automatically at 00:05 GMT +7"
exit 0
}


function stop() {
email=$(cat /home/email)
sed -i "/^$email/d" /home/email
sed -i "/^# BEGIN_Backup/,/^# END_Backup/d" /etc/crontab
service cron restart
sleep 1
echo " Please Wait"
clear
echo " Autobackup Has Been Stopped"
exit 0
}


function recipient() {
rm -rf /home/email
clear
echo ""
echo ""
read -rp " Email    : " -e email
cat <<EOF>>/home/email
$email
EOF
}


function sender() {
echo "Please enter your email"
read -rp " Email    : " -e email
echo ""
echo ""
echo "Please enter your Password email"
read -rp " Password : " -e pwdd
rm -rf /etc/msmtprc
cat<<EOF>>/etc/msmtprc
defaults
tls on
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
account default
host smtp.gmail.com
port 587
auth on
user $email
from $email
password $pwdd
logfile ~/.msmtp.log
EOF
}
function send() {
email=$(cat /home/email)
if [[ "$email" = "" ]]; then
start
fi
email=$(cat /home/email)
echo -e "
Ini adalah isi email percobaaan kirim email dari vps
IP VPS : $IP
Tanggal : $date
" | mail -s "Percobaan Pengiriman Email" $email
}
clear



ENVIRONMENT
L1
echo -e "${97;1m      Autobackup Data${Suffix} $sts     "
L2
L1
echo
echo -e "${R2} 1. Start Autobackup"
echo -e "${R2} 2. Stop Autobackup"
echo -e "${R2} 3. Change Email Recipient"
echo -e "${R2} 4. Change Email Sender"
echo -e "${R2} 5. Test send Email"
echo
L2
echo
read -rp " Select From Options:  " -e num
case $num in
1)
start
;;
2)
stop
;;
3)
recipient
;;
4)
sender
;;
5)
send
;;
*)
clear
;;
esac