#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
clear
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'



function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————— ${Xark} "
}
# . 1
function Create_Account() {
  add-tro
}
# . 2
function Create_Trial() {
  trial-tro
}
# . 3
function Delete_Account() {
  del-tro
}
# . 4
function List_Member() {
  member-tro
}
# . 5
function Renew_Account() {
  renew-tro
}
# . 6
function Changes_Limit() {
  ganti-ip-trojan
}
# . 7 
function Check_Account() {
  cek-tro
}
# . 8 
function Check_Details_Account() {
  user-tro
}


function Menu_Features() {
  echo -e "${UK}      ╔═════${R1}[ XRAY TROJAN ]${UK}══════╗          ${Xark} "        
  echo -e "${UK}      ║${R2}  1]- Create Account    " 
  echo -e "${UK}      ║${R2}  2]- Trial Account     " 
  echo -e "${UK}      ║${R2}  3]- Delete Account    " 
  echo -e "${UK}      ║${R2}  4]- List Member       "       
  echo -e "${UK}      ║${R2}  5]- Renew Account        "    
  echo -e "${UK}      ║${R2}  6]- Change limit Ip     "  
  echo -e "${UK}      ║${R2}  7]- Monitor Account      "  
  echo -e "${UK}      ║${BK}  x]- Exit ${Xark}     "        
  echo -e "${UK}      ╚══════════════════════════${Suffix}"      
}


Menu_Features
read -p "Select [1/7 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Account ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Account ;;
4) clear ; List_Member ;;
5) clear ; Renew_Account ;;
6) clear ; Changes_Limit ;;
7) clear ; Check_Account ;;
*) menu ;;
esac
