#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
clear

LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

ipsaya=$(wget -qO- ipinfo.io/ip)
echo -e "Memeriksa VPS Anda..."
sleep 0.5

KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/@RAIKAZUSTORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282164649858"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc


function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————— ${Xark} "
}

# . 1
function Create_Vless() {
  add-vle
}

# . 2
function Create_Trial() {
  trial-vle
}

# . 4
function List_Member() {
  member-vle
}

# . 3
function Delete_Exp() {
  del-vle
}

function Changes_Limit() {
  limit-Vless
}

# . 5 
function Renew_Account() {
  renew-vle
}

# . 6 
function Check_Account() {
  user-vle
}

# . 7 
function Change_Ip_Limit() {
  ganti-ip-vless
}

# . 8 
function Change_Vless_Quota() {
  change-vless-qouta
}




function Menu_Features() {
  echo -e "${UK}      ╔═════${R1}[ XRAY VLESS ]${UK}══════╗          ${Xark} "        
  echo -e "${UK}      ║${R2}  1]- Create Account    " 
  echo -e "${UK}      ║${R2}  2]- Trial Account     " 
  echo -e "${UK}      ║${R2}  3]- Delete Account    " 
  echo -e "${UK}      ║${R2}  4]- List Member       "       
  echo -e "${UK}      ║${R2}  5]- Renew Account        "    
  echo -e "${UK}      ║${R2}  6]- Change Limit ip      " 
  echo -e "${UK}      ║${R2}  7]- Change Quota      "     
  echo -e "${UK}      ║${BK}  x]- Exit ${Xark}     "        
  echo -e "${UK}      ╚══════════════════════════${Suffix}"      
}


Menu_Features
read -p "Select [1/7 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Vless ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Vless ;;
4) clear ; List_Member ;;
5) clear ; Renew_Account ;;
6) clear ; Change_Ip_Limit ;;
7) clear ; Change_Vless_Quota ;;
*) exit ;;
esac
