#!/bin/bash
# Lt | Project
# ==========================================
# Color
RED='\033[0;31m'
NC='${Suffix}'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

# ==========================================
# Getting
MYIP=$(curl -sS ipv4.icanhazip.com);
clear
echo -e "${UK}┌──────────────────────────────────────────┐${Suffix}"
echo -e "${BC}   USERNAME       EXP DATE         STATUS       ${Suffix}"
echo -e "${UK}└──────────────────────────────────────────┘${Suffix}"
echo -e "${UK}┌──────────────────────────────────────────┐${Suffix}"


while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "LOCKED${NORMAL}"
else
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"


echo -e "${UK}└──────────────────────────────────────────┘${Suffix}"
echo -e "${UK}┌──────────────────────────────────────────┐${Suffix}"
echo -e "${R2}   Account number: $JUMLAH   user               ${Suffix}"
echo -e "${UK}└──────────────────────────────────────────┘${Suffix}"
echo -e ""