#!/bin/bash
MYIP=$(curl -sS ipv4.icanhazip.com)
clear

green='\033[0;32m'
r="\e[91;1m"
RED="\e[91;1m"
Blu_Cy="\e[5;36m"
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

#########################
# USERNAME
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ipv | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
clear

# validity
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ipv | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e
clear

# DETAIL ORDER
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
clear

# CERTIFICATE STATUS
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
clear


mai="datediff "$Exp" "$DATE""
clear
# Status ExpiRED Active | Raikazu Project
Info="${Blu_Cy}【ACTIVATED】${Suffix}"
Error="${RED}【NOT ACTIVATED】${Suffix}"
today=`date -d "0 days" +"%Y-%m-%d"`
Exp1=$(curl -sS https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ipv | grep $MYIP | awk '{print $3}')
if [[ $today < $Exp1 ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear

ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
clear

# STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${green}ON${Suffix}"
else
   status_ssh="${RED}OFF${Suffix} "
fi

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${Blu_Cy}ON${Suffix}"
else
    status_ws_epro="${RED}OFF${Suffix} "
fi

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${green}ON${Suffix}"
else
   status_haproxy="${RED}OFF${Suffix} "
fi

# STATUS SERVICE XRAY
if [[ $xray_service == "running" ]]; then 
   status_xray="${Blu_Cy}ON${Suffix}"
else
   status_xray="${RED}OFF${Suffix} "
fi

# STATUS SERVICE NGINX
if [[ $nginx_service == "running" ]]; then 
   status_nginx="${Blu_Cy}ON${Suffix}"
else
   status_nginx="${RED}OFF${Suffix} "
fi

# STATUS SERVICE Dropbear
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="${Blu_Cy}ON${Suffix}"
else
   status_dropbear="${RED}OFF${Suffix} "
fi
clear

#####INFOAKUN
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
let ssa=$ssx/2
########
clear

function Lt_System() {
clear
echo -e "        ${UK}┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${Suffix}"
echo -e "        ${BC}  ••::::::••  SYSTEM  VPS  ••::::::••       ${Suffix}"
echo -e "        ${UK}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
echo -e "        ${UK}┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${Suffix}"
echo -e "        ${UK}│${BC} SYSTEM OS : $(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')${Suffix}"
echo -e "        ${UK}│${BC} MEMORY USAGE : $(free -m | awk 'NR==2 {print $2}') MB/$(free -m | awk 'NR==2 {print $3}') MB${Suffix}"
echo -e "        ${UK}│${BC} SYSTEM UPTIME : $(uptime -p | cut -d " " -f 2-10000)${Suffix}"
echo -e "        ${UK}│${BC} CORE : $(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")${Suffix}"
echo -e "        ${UK}│${BC} ISP : $(cat /etc/xray/isp)${Suffix}"
echo -e "        ${UK}│${BC} CITY : $(cat /etc/xray/city)${Suffix}"
echo -e "        ${UK}│${BC} IP : $(curl -s ipv4.icanhazip.com)${Suffix}"                                                
echo -e "        ${UK}│${BC} DOMAIN : $(cat /etc/xray/domain)${Suffix}"                                                  
echo -e "        ${UK}|${BC} AUTHOR SCRIPT : @RAIKAZUSTORE${Suffix}"
echo -e "        ${UK}|${BC} WHATSHAPP OWN : 082164649858${Suffix}"
echo -e "        ${UK}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
}


function Status_Service() {
echo -e "  ${UK}┏━━━━━━━━━━━━━•${Suffix}STATUS SERVICE SERVER${UK}•━━━━━━━━━━━━┓${Suffix}"
echo -e "  ${UK}│${Suffix}${BC}【 SSH WS :${Suffix} $status_ws_epro ${Suffix}】${BC}【 XRAY :${Suffix} $status_xray ${Suffix}】${BC}【 NGINX :${Suffix} $status_nginx ${Suffix}】${UK}│${Suffix}"
echo -e "  ${UK}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
}
echo -e ""
echo -e ""
function Details_Account() {
echo -e ""
echo -e "    ${BC}【 SSH Account = $ssh1 】  【 VMESS Account = $vma 】${Suffix}"
echo -e ""
echo -e "  ${BC}【 VLESS Account = $vla  】 【 TROJAN Account = $trb  】${Suffix}"
echo -e ""
}
echo -e ""
function Menu_Display() {
echo -e "     \e[38;5;99m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\e[0m"
echo -e "     \e[38;5;195m                 𝐋𝐈𝐒𝐓 𝐌𝐄𝐍𝐔                \033[0m"
echo -e "     \e[38;5;99m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\e[0m"
echo -e "     ${UK}┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
echo -e "     ${UK}|${Suffix}${UB} 1.${Suffix}${BC}SSH WS【Menu】${Suffix}${UB}       5.${Suffix}${BC}REBOOT 【Menu】${Suffix}  ${UK}│${Suffix}"
echo -e "     ${UK}│${Suffix}${UB} 2.${Suffix}${BC}VMESS 【Menu】${Suffix}${UB}       6.${Suffix}${BC}UPDATE SYSTEM${Suffix}    ${UK}│${Suffix}"
echo -e "     ${UK}│${Suffix}${UB} 3.${Suffix}${BC}VLESS 【Menu】${Suffix}${UB}       7.${Suffix}${BC}BOT TELE【Menu】 ${Suffix}${UK}│${Suffix}"
echo -e "     ${UK}|${Suffix}${UB} 4.${Suffix}${BC}TROJAN【Menu】${Suffix}${UB}       8.${Suffix}${BC}SETTING【Menu】  ${Suffix}${UK}│${Suffix}"
echo -e "     ${UK}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
echo -e ""
echo -e "        ${UK}┏━━━━━━━━━━━━━•${Suffix} 𝙸𝙽𝙵𝙾 ${UK}•━━━━━━━━━━━━━━┓${Suffix}"
echo -e "        ${UK}|${Suffix} ${BC}VERSI SCRIPT :${Suffix}${Blu_Cy} VIP VERSION${Suffix}"
echo -e "        ${UK}│${Suffix} ${BC}NAMA CLIENT  :${Suffix}${BC} $(cat /usr/bin/user)${Suffix}"
echo -e "        ${UK}│${Suffix} ${BC}OWNER SCRIPT :${Suffix}${BC} RAIKAZU STORE${Suffix}"
echo -e "        ${UK}│${Suffix} ${BC}STATUS SCRIPT :${Suffix}${BC} $sts${Suffix}"
echo -e "        ${UK}│${Suffix} ${BC}DURASI SCRIPT:${Suffix} ${BC}$(((d1 - d2) / 86400)) DAYS${Suffix}"
echo -e "        ${UK}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
}
echo -e ""
echo -e ""
echo -e ""
function Select_Display() {
echo -e ""
read -p "              SELECT MENU : " opt
echo -e ""
case $opt in
1 | 01)
clear
m-ssh
;;
2 | 02)
clear
m-vme
;;
3 | 03)
clear
m-vle
;;
4 | 04)
clear
m-tro
;;
5 | 05)
clear
autoreboot
;;
6 | 06)
clear
update
;;
7 | 07)
clear
add-bot-panel
;;
8 | 08)
clear
m-ftr
;;
*)
clear
menu
;;
esac
}

Lt_System
Status_Service
Details_Account
Menu_Display
Select_Display