#!/bin/bash
# Color Type 9
CY="\e[96;1m" # Cyan
CyanBee="\e[5;36m" # BlueCyan
GreenBe="\e[5;32m" # Green / hijau
WhiteBe="\e[5;37m" # White / Putih
Green="\e[92;1m"

# Color type 38
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

# . Liner L1
function L1() {
  echo -e "${UK}┌──────────────────────────────────────────┐ ${Suffix} "
}


# . Liner L2
function L2() {
  echo -e "${UK}└──────────────────────────────────────────┘ ${Suffix}"
}


# . Liner Horizontal
function Horizontal(){
  echo -e "${UK}———————————————————————————————————————————      ${Suffix}"
}

  
  # // Lunatic Backend Banner
function Lunatic_Banner() {
clear
L1
echo -e "${CyanBee}              RAIKAZU STORE                   ${Suffix}"
L2
}

  # // Thanks To Lunatic Tunneling
function Sc_Credit(){
sleep 2
L1
echo -e "${CyanBee}       Terimakasih Telah Menggunakan-      ${Suffix}"
echo -e "${CyanBee}                Script Credit              ${Suffix}"
echo -e "${CyanBee}                RAIKAZU STORE                   ${Suffix}"
L2
read -p "[Enter] Back Menu "
menu
}

function ENVIRONMENT() {
L1
 echo -e "${R2}           ---[ INPUT MINUTES ]---             ${Suffix}"
L2
}

# // Submit Loading : sleep 3 & loading $!
function loading() {
clear
echo
echo
echo
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

function Format_Just_Input() {
Lunatic_Banner
L1
echo ""
echo -e "${GreenBe} Just Input a number ${Suffix}"
echo -e "${WhiteBe} Format Number in day${Suffix}"
echo -e ""
echo -e "${CyanBee} 1 = 1 day ${Suffix}"
echo -e "${CyanBee} 2 = 2 day ${Suffix}"
echo ""
L2
echo ""
}



# Getting Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"

# // Systen
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
clear
IP=$(curl -sS ipv4.icanhazip.com)

# // Frint Trial
Login=TrI4L`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=7
iplimit=10


# // Get Ip Limit Ssh
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null


# // Frint Logo
Lunatic_Banner
ENVIROMENT
Format_Just_Input

# // input Settings
read -p " Input Minutes   :  " pup

# // Frint Load
sleep 2 & loading $!


CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="<code>---------------------------------------------------</code>
<code>Your Premium VPN Details</code>
<code>---------------------------------------------------</code>
<code>IP Address    =</code> <code>$IP</code>
<code>Hostname      =</code> <code>$domain</code>
<code>Username      =</code> <code>$Login</code>
<code>Password      =</code> <code>$Pass</code>
<code>---------------------------------------------------</code>
<code>OpenSSH       = 22
Dropbear      = 443, 109, 143
SSL/TLS       = 400-900
SSH WS TLS    = 443
SSH WS NTLS   = 80, 8080, 8081-9999
OVPN WS NTLS  = 80, 8080, 8880
OVPN WS TLS   = 443
BadVPN UDP    = 7100,7200,7300</code>
<code>---------------------------------------------------</code>
Ovpn Download : https://$domain:81/
<code>---------------------------------------------------</code>
Save Link Account: https://$domain:81/ssh-$Login.txt
<code>---------------------------------------------------</code>
Berakhir Pada  : $pup Menit
<code>---------------------------------------------------</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo ""
mkdir -p /etc/ssh

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${Login} " >>/etc/ssh/.ssh.db
echo ""
cat > /var/www/html/ssh-$Login.txt <<-END
---------------------------------------------------
Format SSH OVPN Account
---------------------------------------------------
Username         : $Login
Password         : $Pass
Berakhir Pada  : $pup Menit
---------------------------------------------------
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
---------------------------------------------------
Payload : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
---------------------------------------------------
OVPN Download : https://$domain:81/
---------------------------------------------------

END
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf] "




# // Get Account Detail
function Ssh_Details(){
clear
Horizontal
echo " SSH OPENVPN "
echo ""
echo " Remark   : ${Login}"
echo " pasword  : ${Pass}"
echo " limit ip : ${iplimit}"
echo " Domain   : ${domain}"
echo " Port Udp : 1-65535 "
echo " Port WS  : 80,8880,2082,8080"
echo " Port Tls : 443,8443 "
echo " OpenSSH  : 22,143 "
echo " OVPN Tls : 443 "
echo " Ovpn UdP : 2200 "
echo " Ovpn Tcp : 443"
Horizontal
}



# // Get Payload Detail 
function Payload_Details(){
Horizontal
echo " Payload WS    : ${PAYLOADWS}     ${Suffix}"
Horizontal
echo " Payload Tls   : ${PAYLOADTLS}    ${Suffix}"
Horizontal
echo " Payload Hnced : ${PAYLOADHANCED} ${Suffix}"
Horizontal
}


# // Get Expired Account
function Expiry_Account(){
echo -e "${R2} Expiry in  : ${pup} "
Horizontal
}



# // Frint Info Ssh
Ssh_Details
Payload_Details
Expiry_Account

# // Frint Thanks Raikazu
Sc_Credit
echo "userdel -f \"$Login\"" | at now + $pup minutes &> /dev/null