#!/bin/bash
DF='\e[39m'
RED='\033[0;31m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
putih="\e[1;97m"
BGX="\e[104m"
blue="\e[1;96m"
NC='\e[0m'
RED='\033[0;31m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lyellow='\e[93m'
Lgreen='\e[92m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
UK='\e[38;5;99m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# STATUS SERVICE  BOT 
cybervpn_service=$(systemctl status cybervpn | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

if [[ $cybervpn_service == "running" ]]; then 
   status_bot="${GREEN}RUNNING🔥$NC${c} $NC"
else
   status_bot="${RED}ERROR🔥{NC} "
fi
#####
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/@RAIKAZUSTORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282164649858"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc

echo -e "\e[32mloading...\e[0m"
clear
MYIP=$(wget -qO- ipinfo.io/ip);
clear 
echo -e "${UK}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih} ${BGX}             WELCOME TO PROJECT RAIKAZU V1             ${NC}"
echo -e "${UK}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${KIRI}   ${putih}STATUS BOT${NC} ( ${status_bot} )"
echo -e ""
echo -e " [01]  ${putih}INSTALL BOT PANEL${NC}"
echo -e " [02]  ${putih}INSTALL BOT NOTIF${NC}"
echo -e " [03]  ${putih}MANAGER BOT PANEL${NC}"
echo -e "" 
echo -e " [00]   ${putih}ENTER GO BACK MENU${NC}"
echo -e "${UK}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
read -p " Select menu :  "  opt
echo -e   ""
case $opt in
01 | 1) clear ; wget -q https://raw.githubusercontent.com/RaikazuWebId/vpnscript/refs/heads/mytich/bot/bot.sh && chmod +x bot.sh && ./bot.sh ;;
02 | 2) clear ; add-bot-notif ;;
03 | 3) clear ; panelbot.sh ;;
00 | 0) clear ; menu ;;
*) clear ; menu ;;
esac
