#!/bin/bash


BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'

runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'


clear

function Menu_Features() {
  echo -e "${UK}      ╔═════${R1}[ BACKUP VPS ]${UK}══════╗          ${Xark} "        
  echo -e "${UK}      ║${R2}  1]- Backup Vps Data    " 
  echo -e "${UK}      ║${R2}  2]- Restore Vps Data    " 
  echo -e "${UK}      ║${R2}  3]- AutoBackup    "   
  echo -e "${UK}      ║${BK}  x]- Exit ${Xark}     "        
  echo -e "${UK}      ╚══════════════════════════${Suffix}"      
}



function Backup_Vps() {
  backup
}


function Restore_Vps() {
  restore
}


function Auto_Backup_Vps() {
  autobackup
}



Menu_Features
read -p "Select [1/3 or x] :  " Ltt
case $Ltt in
1) clear ; Backup_Vps ;;
2) clear ; Restore_Vps ;;
3) clear ; Auto_Backup_Vps ;;
*) exit ;;
esac
