#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
White="\033[97;1m"
Green="\033[92;1m"
Cyan="\033[96;1m"
Xark='\e[0m'

runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
BR='\033[0;0;44m' # BIRU CERAH
Suffix='\e[0m'
NC='\e[0m'

ipsaya=$(wget -qO- ipinfo.io/ip)
echo -e "Memeriksa VPS Anda..."
sleep 0.5

KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/@RAIKAZUSTORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282164649858"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc

BG_BLU="\033[44;1m" # BG BIRU
clear
echo -e ""
echo -e " ${UK}───────────────────────────────────────${Suffix}"
echo -e " ${BC}              MENU FITUR TAMBAHAN           ${Suffix}"
echo -e " ${UK}───────────────────────────────────────${Suffix}"
echo -e " \033[0m [01] Check Bandwidth${NC}"      
echo -e " \033[0m [02] Check All Service${NC}"
echo -e " \033[0m [03] Restart All Service${NC}"
echo -e " \033[0m [04] Reboot VPS${NC}"
echo -e " \033[0m [05] RAM Usage${NC}"
echo -e " \033[0m [06] Speed VPS${NC}"
echo -e " \033[0m [07] Change Banner${NC}"
echo -e " \033[0m [08] Update Script${NC}"
echo -e " \033[0m [09] Menu Noobzvpn${NC}"
echo -e " \033[0m [10] Fix Missing Pointing Domain${NC}"
echo -e " \033[0m [11] Subdomain Web.id${NC}"
echo -e " \033[0m [12] Change Domain VPS${NC}"
echo -e " \033[0m [13] Auto backup Configuration VPS${NC}"
echo -e " \033[0m [14] Backup Configuration VPS${NC}"
echo -e " \033[0m [15] Restore Configuration VPS${NC}"
echo -e " \033[0m [16] Clear Log${NC}"
echo -e " \033[0m [17] Clear Cache${NC}"
echo -e " \033[0m [18] Delete All Account Exp${NC}"
echo -e " \033[0m [19] SlowDNS${NC}"
echo -e " \033[0m [20] Streaming Support Checker${NC}"
echo -e " \033[0m [21] Limit Speed${NC}"
echo -e " \033[0m [22] Information System${NC}"
echo -e " \033[0m [23] Install Bot Panel${NC}"
echo -e " \033[0m [24] Install UDP CUSTOM${NC}"
echo -e " \033[0m [25] Fix Haproxy${NC}"
echo -e " \033[0m [26] Fix Dropbear${NC}"
echo -e " \033[0m [27] Autoreboot${NC}"
echo -e " \033[0m [28] Hapus Akun Trial${NC}"
echo -e " \033[0m  x.) Exit${NC}"
echo -e ""
echo -e " ${UK}───────────────────────────────────────${Suffix}"
echo -e " ${UK}───────────────────────────────────────${Suffix}"
echo -e ""
function Select_Display() {
read -p " Select From Options [1-22 or x]: " menu
echo -e ""
case $menu in
1)
    clear
    vnstat -d
    ;;
2)
   clear
   run
   ;;
3)
   clear
   reset
   ;;
4)
   clear
   reboot
   ;;
5)
   clear
   gotop
   ;;
6)
   clear
   speedtest
   ;;
7)
    clear
    nano /etc/issue.net
    ;;
8)
    clear
    update
    ;;
9)
    clear
    menu-noob
    ;;
10)
    clear
    fixcert
    ;;
11)
    clear
    cf.web.id
    ;;
12)
    clear
    change-domain
    ;;
13)
    clear
    autobackup
    ;;
14)
    clear
    backup
    ;;                
15)
    clear
    restore
    ;;
16)
    clear
    clearlog
    ;;
17)
    clear
    clearcache
    ;;
18)
    clear
    xp
    ;;
19)
    clear
    echo -e "coming soon"
    ;;
20)
    clear
    wget https://raw.githubusercontent.com/Jengkolonline/nonton/main/nf.sh && chmod +x nf.sh && ./nf.sh
    ;;
21)
    clear
    limitspeed
    ;;
22)
    clear
    neo
    ;;
23)
    clear
    panelbot.sh
   ;; 
24)
   clear
   UDEPE
   ;;
25)
   clear
   fixhap
   ;;
26)
   clear
   systemctl restart dropbear
   ;;
27)
   clear
   autoreboot
   ;;
*)
    clear
    menu
    ;;
esac
}

Select_Display