#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
clear

LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'


clear

function L1() {
  echo -e "${UK} ╔═══════════════════════════════════════════════╗${Suffix}"
}

  
function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————— ${Xark} "
}


# . 1
function Create_Account() {
  add-ssr
}

# . 2
function Create_Trial() {
  trial-ssr
}

# . 3
function List_Member() {
  member-ssr
}

# . 4
function Delete_Account() {
  delet-ssr
}

# . 5
function Changes_Limit() {
  change-limit-xray
}

# . 6
function Renew_Account() {
  renew-ssr
}

function Monitor_Ssr(){
 cek-ssr
}

function Menu_Features() {
  echo -e "${UK}      ╔═════${R1}[ SHADOWSOCKS ]${UK}══════╗          ${Xark} "        
  echo -e "${UK}      ║${R2}  1]- Create Account    " 
  echo -e "${UK}      ║${R2}  2]- Trial Account     " 
  echo -e "${UK}      ║${R2}  3]- Delete Account    " 
  echo -e "${UK}      ║${R2}  4]- List Member       "       
  echo -e "${UK}      ║${R2}  5]- Renew Account        "    
  echo -e "${UK}      ║${R2}  6]- Monitor Account      "    
  echo -e "${UK}      ║${BK}  x]- Exit ${Xark}     "        
  echo -e "${UK}      ╚══════════════════════════${Suffix}"      
}


Menu_Features
read -p "Select [1/6 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Account ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Account ;;
4) clear ; List_Member ;;
5) clear ; Renew_Account ;;
6) clear ; Monitor_Ssr ;;
*) menu ;;
esac
