#!/bin/bash

BR='\e[94;1m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'

runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

clear

function L1() {
  echo -e "${UK} ╔═══════════════════════════════════════════════╗${Suffix}"
}


function L2() {
  echo -e "${UK} ╚═══════════════════════════════════════════════╝${Suffix}"
}



# . Create Ssh
function Create_Ssh() {
  add-ssh
}

# . Create Triall
function Create_Trial() {
  trial-ssh
}

# . Hapus akun ssh
function Delete_Ssh(){
  del-ssh
}

# . List Member ssh
function List_Member() {
  member-ssh
}

# . Auto Kill ssh
function Auto_Kill() {
  auto-kill
}

# . Check user Login
function Check_Mullog() {
  ceklim
}

# . Delete Expiry
function Delete_Exp() {
  delexp
}

# . Changes Limit
function Changes_Limit() {
  Lt-on-off
}

# . Limit On off
function Limit_On_Off() {
  limit-on-off
}

#. Renew Ssh
function Renew_Ssh() {
  renew-ssh
}

# . Lock Ssh
function Lock() {
  lock
}

# . Unlock Ssh
function Unlock() {
  unlock
}

# . Detail Akun Ssh
function Details_Account(){
  user-ssh
}

function Monitor_Ssh() {
  cek-ssh
}


function Menu_Features() {
  echo -e "${BR}      ╔═════${BC}[ SSH OPENVPN ]${BR}══════╗          ${Xark} "        
  echo -e "${BR}      ║${BC}  1]- Create Account    " 
  echo -e "${BR}      ║${BC}  2]- Trial Account     " 
  echo -e "${BR}      ║${BC}  3]- Delete Account    " 
  echo -e "${BR}      ║${BC}  4]- List Member       "       
  echo -e "${BR}      ║${BC}  5]- Auto Kill User    "       
  echo -e "${BR}      ║${BC}  6]- Check MultiLogin  "       
  echo -e "${BR}      ║${BC}  7]- Delete Expiry Account"    
  echo -e "${BR}      ║${BC}  8]- Changes Limit Account"    
  echo -e "${BR}      ║${BC}  9]- Renew Account        "    
  echo -e "${BR}      ║${BC} 10]- Locked Account       "    
  echo -e "${BR}      ║${BC} 11]- Unlock Account       "    
  echo -e "${BR}      ║${BC} 12]- Limit On Off         "    
  echo -e "${BE}      ║${BC} 13]- Monitor Account      "    
  echo -e "${BR}      ║${BK}  x]- Exit ${Xark}     "        
  echo -e "${BR}      ╚══════════════════════════${Suffix}"      
}

Menu_Features
read -p "Select From Options [1/13 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Ssh ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Ssh ;;
4) clear ; List_Member ;;
5) clear ; Auto_Kill ;;
6) clear ; Check_Mullog ;;
7) clear ; Delete_Exp ;;
8) clear ; Changes_Limit ;;
9) clear ; Renew_Ssh ;;
10) clear ; Lock ;;
11) clear ; Unlock ;;
12) clear ; Limit_On_Off ;;
13) clear ; Monitor_Ssh ;;
*) menu ;;
esac
