#!/bin/bash
# Color Type 9
CY="\e[96;1m" # Cyan
CyanBee="\e[5;36m" # BlueCyan
# Color type 38
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

# . Liner L1
function L1() {
  echo -e "${UK}┌──────────────────────────────────────────┐ ${Suffix} "
}


# . Liner L2
function L2() {
  echo -e "${UK}└──────────────────────────────────────────┘ ${Suffix}"
}
  
  # // Raikazu Backend Banner
function Raikazu_Banner() {
clear
L1
echo -e "${CyanBee}              RAIKAZU STORE                   ${Suffix}"
L2
}

  # // Thanks To Raikazu Tunneling
function Sc_Credit(){
sleep 2
L1
echo -e "${CyanBee}       Terimakasih Telah Menggunakan-      ${Suffix}"
echo -e "${CyanBee}                Script Credit              ${Suffix}"
echo -e "${CyanBee}                RAIKAZU STORE              ${Suffix}"
L2
read -p "[Enter] Back Menu "
menu
}

function List_Member() {
L1
 echo -e "${R2}           ---[ LIST MEMBER ]---             ${Suffix}"
L2
}



# Function to display menu
display_menu() {
    echo "=== NoobzVpn-Server Menu ==="
    echo "1. Install NoobzVpn-Server"
    echo "2. Add User"
    echo "3. Block User"
    echo "4. Unblock User"
    echo "5. Set Expiration"
    echo "6. Renew Expiration"
    echo "7. Change Password"
    echo "8. Rename User"
    echo "9. Remove User"
    echo "10. Remove All Users"
    echo "11. Info User"
    echo "12. Info All Users"
    echo "13. Exit"
}

# Function to install NoobzVpn-Server
install_noobzvpn_server() {
    echo "Starting NoobzVpn-Server installation..."
    # Your installation commands go here
    echo "NoobzVpn-Server installed successfully."
}

# Function to add a new user
add_user() {
    read -p "Input username : " username
    echo ""
    read -p "Input password : " password
    echo ""
    read -p "Input Expired  : " days
    noobzvpns --add-user "$username" "$password"
    noobzvpns --expired-user "$username" "$days"
}

# Function to block a user
block_user() {
Lunatic_Banner
echo ""
    read -p "Enter username to block: " username
    noobzvpns --block-user "$username"
}

# Function to unblock a user
unblock_user() {
Lunatuc_Banner
echo ""
    read -p "Enter username to unblock: " username
    noobzvpns --unblock-user "$username"
}

# Function to set expiration for a user
set_expiration() {
Lunatic_Banner
echo ""
    read -p "Enter username: " username
    read -p "Enter expiration days (0 for unlimited): " days
    noobzvpns --expired-user "$username" "$days"
}

# Function to renew expiration for a user
renew_expiration() {
Lunatic_Banner
echo ""
    read -p "Enter username to renew expiration: " username
    noobzvpns --renew-user "$username"
}


# Function to change password for a user
change_password() {
Lunatic_Banner
echo ""
    read -p "Enter username     :  " username
echo ""
    read -p "Enter new password :  " new_password
    noobzvpns --password-user "$username" "$new_password"
}

# Function to rename a user
rename_user() {
Lunatic_Banner
echo ""
    read -p "Enter current username: " old_username
echo ""
    read -p "Enter new username: " new_username
    noobzvpns --rename-user "$old_username" "$new_username"
}

# Function to remove a user
remove_user() {
Lunatic_Banner
echo ""
    read -p "Input username to remove: " username
    noobzvpns --remove-user "$username"
}

# Function to remove all users
remove_all_users() {
Lunatic_Banner
echo ""
    read -p "Are you sure you want to remove all users? (yes/no): " confirm
    if [ "$confirm" == "yes" ]; then
        noobzvpns --remove-all-user
    else
        echo "Operation cancelled."
    fi
}

# Function to get info for a user
info_user() {
Lunatic_Banner
echo ""
    read -p "Enter username: " username
    noobzvpns --info-user "$username"
}

# Function to get info for all users
info_all_users() {
    noobzvpns --info-all-user
}

# Main script
while true; do
    display_menu
    read -p "Enter your choice: " choice
    case $choice in
        1) install_noobzvpn_server ;;
        2) add_user ;;
        3) block_user ;;
        4) unblock_user ;;
        5) set_expiration ;;
        6) renew_expiration ;;
        7) change_password ;;
        8) rename_user ;;
        9) remove_user ;;
        10) remove_all_users ;;
        11) info_user ;;
        12) info_all_users ;;
        13) exit ;;
        *) echo "Invalid choice. Please enter a number between 1 and 13." ;;
    esac
done
