#!/bin/bash
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')
#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear

BR='\e[94;1m'
green='\033[0;32m'
r="\e[91;1m"
RED="\e[91;1m"
Blu_Cy="\e[5;36m"
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'


######################################
# // USERNAME IZIN IPP
url_izin="https://raw.githubusercontent.com/RaikazuWebId/izinsc/main/ip"
rm -f /usr/bin/user
username=$(curl -sS $url_izin | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS $url_izin | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
#certifacate=$(((d1 - d2) / 86400))
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\e[38;5;196mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\e[38;5;196mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\e[38;5;196mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\e[38;5;196mOFF${NC} "
fi

loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

res1() {
systemctl restart dropbear
}
echo -e "\e[94;1m  ╔══════════════════════════════════╗\e[0m"
echo -e "${BR}              PLEASE WAIT !! ${Suffix}"
echo -e "\e[94;1m  ╚══════════════════════════════════╝\e[0m"
loading 'res1'
clear

function RZ_Banner() {
echo -e   "\e[94;1m  ╔═════════════════════════════════════════════════╗\e[0m"
echo -e     "\e[96;1m            ----[ RAIKAZU PROJECT V1 ]----                   \e[0m"
echo -e   "\e[94;1m  ╚═════════════════════════════════════════════════╝\e[0m"
}


function Service_Status() {
echo -e "  ${BR}┏━━━━━━━━━━━━━•${BC}STATUS SERVICE SERVER${Suffix}${BR}•━━━━━━━━━━━━┓${Suffix}"
echo -e "  ${BR}│${Suffix}${BC}【 SSH WS :${Suffix} $status_ws_epro ${Suffix}】${BC}【 XRAY :${Suffix} $status_xray ${Suffix}】${BC}【 NGINX :${Suffix} $status_nginx ${Suffix}】${BR}│${Suffix}"
echo -e "  ${BR}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
}

echo -e ""
function Details_Clients_Name() {
echo -e "        ${BR}┏━━━━━━━━━━━━━• ${BC}𝙸𝙽𝙵𝙾 ${Suffix}${BR}•━━━━━━━━━━━━━━┓${Suffix}"
echo -e "        ${BR}|${Suffix} ${BC}VERSI SCRIPT :${Suffix}${Blu_Cy} VIP VERSION${Suffix}"
echo -e "        ${BR}│${Suffix} ${BC}NAMA CLIENT  :${Suffix}${BC} $(cat /usr/bin/user)${Suffix}"
echo -e "        ${BR}│${Suffix} ${BC}OWNER SC     :${Suffix}${BC} RAIKAZU STORE${Suffix}"
echo -e "        ${BR}│${Suffix} ${BC}DURASI SCRIPT:${Suffix}${BC}$(((d1 - d2) / 86400)) DAYS${Suffix}"
echo -e "        ${BR}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${Suffix}"
}
echo -e ""
echo -e ""
function Acces_Use_Command() {
echo -e "       ${BR}┌──────────────────────────────────────┐${Suffix}"
echo -e "       ${BC}       --[ ENTER TO OPEN MENU ]--${Suffix} " 
echo -e "       ${BR}└──────────────────────────────────────┘${Suffix}"
echo ""
}

function Open_Menu() {
echo -e ""
read -n 1 -s -r -p "--"
menu
}

RZ_Banner
Service_Status
Details_Clients_Name
Acces_Use_Command
Open_Menu